---
name: tethys
kind: pipeline
type: docker

steps:
  - name: greeting
    image: alpine
    commands:
      - echo 'Hello from ${DRONE_STAGE_MACHINE}'

node:
  m_name: tethys

---
name: main-web
kind: pipeline
type: docker

steps:
  - name: greeting
    image: alpine
    commands:
      - echo 'Hello from ${DRONE_STAGE_MACHINE}'

node:
  m_name: main-web

---
name: oracle-mini-1
kind: pipeline
type: docker

steps:
  - name: greeting
    image: alpine
    commands:
      - echo 'Hello from ${DRONE_STAGE_MACHINE}'

node:
  m_name: oracle-mini-1

---
name: oracle-mini-2
kind: pipeline
type: docker

steps:
  - name: greeting
    image: alpine
    commands:
      - echo 'Hello from ${DRONE_STAGE_MACHINE}'

node:
  m_name: oracle-mini-2

---
name: oracle-arm-1
kind: pipeline
type: docker

platform:
  arch: arm64

steps:
  - name: greeting
    image: alpine
    commands:
      - echo 'Hello from ${DRONE_STAGE_MACHINE}'

node:
  m_name: oracle-arm-1
